name: pytest

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    environment:
      name: development

    steps:
      - uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build the containers & Start the containers
        run: |
          docker-compose -f docker-compose.yml --env-file .env up --build -d

      - name: Test with pytest
        run: |
          docker-compose -f docker-compose.yml --env-file .env exec -T project pytest

      - name: Clean up
        if: always()
        run: |
          docker-compose -f docker-compose.yml --env-file .env down
